/**
 * crawl.js — Playwright-based wiki page crawler.
 *
 * Navigates to GW2 wiki skill/trait pages, toggles WvW mode,
 * and extracts rendered fact data from the blockquote infobox.
 */

const { parseFactText } = require("./parse-facts");

// All wiki DOM selectors in one place for easy maintenance
const SELECTORS = {
  // Game mode toggle buttons (generated by wiki JS)
  gameModeButton: "button.gmvbutton",
  // WvW button: data-mode contains "wvw"
  wvwButton: 'button.gmvbutton[data-mode*="wvw"]',
  // The blockquote containing skill/trait description and facts
  blockquote: ".mw-parser-output blockquote",
  // Fact rows inside the blockquote
  factRow: "blockquote dl > dd",
  // Game-mode-tagged content wrapper
  gameModeDiv: ".gamemode",
  // Disambiguation page indicator
  disambigBox: ".disambig, .dmbox",
  // "Page does not exist" indicator
  noArticle: ".noarticle",
  // Skill/trait infobox
  infobox: ".infobox.skill, .infobox.trait",
};

const WIKI_BASE = "https://wiki.guildwars2.com/wiki/";
const PAGE_TIMEOUT = 10_000;
const RETRY_DELAY = 2_000;

/**
 * Crawl a single entity's wiki page and extract WvW facts.
 * Retries once on network error after a 2-second delay.
 *
 * @param {import('playwright').Page} page — reusable Playwright page
 * @param {object} entity — { id, name, professions }
 * @param {string} entityType — "skill" or "trait"
 * @returns {object} { hasToggle, wvwFacts, error, wiki_url }
 */
async function crawlEntity(page, entity, entityType) {
  for (let attempt = 0; attempt < 2; attempt++) {
    const result = await _crawlEntityOnce(page, entity, entityType);
    if (!result.error || attempt === 1) return result;
    // Retry after delay on first failure
    await new Promise((r) => setTimeout(r, RETRY_DELAY));
  }
}

async function _crawlEntityOnce(page, entity, entityType) {
  const wikiName = entity.name.replace(/ /g, "_");
  // Use encodeURI (not encodeURIComponent) to preserve valid URL chars like ()
  const url = `${WIKI_BASE}${encodeURI(wikiName)}`;
  let finalUrl = url;

  try {
    await page.goto(url, { timeout: PAGE_TIMEOUT, waitUntil: "domcontentloaded" });

    // Wait for wiki JS to potentially generate toggle buttons
    await page.waitForTimeout(500);

    // Check for disambiguation page
    const isDisambig = await page.$(SELECTORS.disambigBox);
    if (isDisambig) {
      // Try profession-qualified URL
      const profession = entity.professions?.[0];
      if (profession) {
        const qualifiedUrl = `${WIKI_BASE}${encodeURI(wikiName + "_(" + profession + ")")}`;
        await page.goto(qualifiedUrl, { timeout: PAGE_TIMEOUT, waitUntil: "domcontentloaded" });
        await page.waitForTimeout(500);
        finalUrl = qualifiedUrl;
        const stillDisambig = await page.$(SELECTORS.disambigBox);
        if (stillDisambig) {
          return { hasToggle: false, wvwFacts: [], error: "Disambiguation page (even with profession qualifier)" };
        }
      } else {
        return { hasToggle: false, wvwFacts: [], error: "Disambiguation page" };
      }
    }

    // Check for missing page
    const noArticle = await page.$(".mw-newarticletext");
    if (noArticle) {
      return { hasToggle: false, wvwFacts: [], error: "Page does not exist" };
    }

    // Check for game mode toggle
    const wvwButton = await page.$(SELECTORS.wvwButton);
    const hasToggle = !!wvwButton;

    if (wvwButton) {
      await wvwButton.click();
      // Wait for CSS visibility changes to apply
      await page.waitForTimeout(300);
    }

    // Extract facts from blockquote
    const wvwFacts = await extractFacts(page, hasToggle);

    return { hasToggle, wvwFacts, error: null, wiki_url: finalUrl };
  } catch (err) {
    return { hasToggle: false, wvwFacts: [], error: err.message };
  }
}

/**
 * Extract fact data from the rendered blockquote.
 *
 * After WvW mode is selected, only WvW-tagged facts and universal facts
 * are visible (PvE facts have display:none). We read all visible <dd> rows.
 */
async function extractFacts(page, hasToggle) {
  return page.$$eval("blockquote dl > dd", (rows, _hasToggle) => {
    const facts = [];

    for (const dd of rows) {
      // Skip hidden elements — the wiki uses a dynamic stylesheet to set
      // display:none on inactive game modes, so check computed style
      const ddStyle = window.getComputedStyle(dd);
      if (ddStyle.display === "none") continue;

      // Check for gamemode wrapper — if it exists and is hidden, skip
      const gmDiv = dd.querySelector(".gamemode");
      if (gmDiv) {
        const style = window.getComputedStyle(gmDiv);
        if (style.display === "none") continue;
      }

      // Extract the fact name from the <a> tag
      const link = dd.querySelector("a[title]");
      if (!link) continue;
      const name = link.textContent.trim();
      if (!name) continue;

      // Extract the full text content after the link
      // Get the text of the dd (or the visible gamemode div)
      const container = gmDiv || dd;
      const fullText = container.textContent.trim();

      // The value portion is everything after "Name:" or "Name (Ns):"
      // Remove the fact name from the beginning, and strip the "?" tooltip
      let valueText = fullText;
      const nameIdx = valueText.indexOf(name);
      if (nameIdx >= 0) {
        valueText = valueText.slice(nameIdx + name.length);
      }
      // Strip leading colon and whitespace
      valueText = valueText.replace(/^\s*:\s*/, "").replace(/\?\s*$/, "").trim();

      facts.push({ name, valueText });
    }

    return facts;
  }, hasToggle);
}

module.exports = { crawlEntity, SELECTORS, WIKI_BASE };
