"use strict";
// Alphabetically sorted relic labels.
// Source: GW2 in-game relics list
// MUST be kept in sync when relics are added/removed.
module.exports = [
  "Relic of Agony",
  "Relic of Akeem",
  "Relic of Altruism",
  "Relic of Antitoxin",
  "Relic of Atrocity",
  "Relic of Bava Nisos",
  "Relic of Bloodstone",
  "Relic of Castora",
  "Relic of Cerus",
  "Relic of Dagda",
  "Relic of Durability",
  "Relic of Dwayna",
  "Relic of Evasion",
  "Relic of Febe",
  "Relic of Fire",
  "Relic of Fireworks",
  "Relic of Fog",
  "Relic of Geysers",
  "Relic of Isgarren",
  "Relic of Karakosa",
  "Relic of Leadership",
  "Relic of Lyhr",
  "Relic of Mabon",
  "Relic of Mercy",
  "Relic of Mistburn",
  "Relic of Mosyn",
  "Relic of Mount Balrior",
  "Relic of Nayos",
  "Relic of Nourys",
  "Relic of Peitha",
  "Relic of Resistance",
  "Relic of Reunification",
  "Relic of Rivers",
  "Relic of Shackles",
  "Relic of Sorrow",
  "Relic of Speed",
  "Relic of Surging",
  "Relic of Thorns",
  "Relic of Vampirism",
  "Relic of Vass",
  "Relic of Zakiros",
  "Relic of the Adventurer",
  "Relic of the Afflicted",
  "Relic of the Alliance",
  "Relic of the Aristocracy",
  "Relic of the Astral Ward",
  "Relic of the Beehive",
  "Relic of the Biomancer",
  "Relic of the Blightbringer",
  "Relic of the Brawler",
  "Relic of the Cavalier",
  "Relic of the Centaur",
  "Relic of the Chronomancer",
  "Relic of the Citadel",
  "Relic of the Claw",
  "Relic of the Coral Heart",
  "Relic of the Daredevil",
  "Relic of the Deadeye",
  "Relic of the Defender",
  "Relic of the Demon Queen",
  "Relic of the Dragonhunter",
  "Relic of the Eagle",
  "Relic of the Earth",
  "Relic of the Firebrand",
  "Relic of the First Revenant",
  "Relic of the Flock",
  "Relic of the Forest Dweller",
  "Relic of the Founding",
  "Relic of the Fractal",
  "Relic of the Golemancer",
  "Relic of the Herald",
  "Relic of the Holosmith",
  "Relic of the Ice",
  "Relic of the Krait",
  "Relic of the Lich",
  "Relic of the Living City",
  "Relic of the Midnight King",
  "Relic of the Mirage",
  "Relic of the Mist Stranger",
  "Relic of the Mists Tide",
  "Relic of the Monk",
  "Relic of the Nautical Beast",
  "Relic of the Necromancer",
  "Relic of the Nightmare",
  "Relic of the Ogre",
  "Relic of the Pack",
  "Relic of the Phenom",
  "Relic of the Pirate Queen",
  "Relic of the Privateer",
  "Relic of the Reaper",
  "Relic of the Scoundrel",
  "Relic of the Scourge",
  "Relic of the Sorcerer",
  "Relic of the Steamshrieker",
  "Relic of the Stormsinger",
  "Relic of the Sunless",
  "Relic of the Thief",
  "Relic of the Trooper",
  "Relic of the Twin Generals",
  "Relic of the Unseen Invasion",
  "Relic of the Warrior",
  "Relic of the Water",
  "Relic of the Wayfinder",
  "Relic of the Weaver",
  "Relic of the Wizard's Tower",
  "Relic of the Zephyrite",
];
